server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/client
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update